name: repobeats

on:
  schedule:
    - cron: "0 0 * * *" # 每天半夜 12 点自动刷新
  workflow_dispatch:    # 允许你随时手动点击刷新

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repobeats
        uses: athul/repobeats@v1.5 # 核心自动化工具
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # 可选配置（直接照抄）
          custom-title: 🚀 Projects I've Contributed To
          hide-private: true
